title: <p align="center"> Raghavendra </p>
       <p align="center"> Srinivasan </p>
logo: /assets/img/Logo.jpg

description:
<p align = "center">


<br>   
I am working on Data Science and RPA related problems.
Working for rSutra Analytics and Consulting Pvt. Ltd.
Having 1.5+ years of experience as Data Analyst and RPA Developer.
</br>
</p>



theme: jekyll-theme-minimal
