title: <p align = "center">Raghavendra </p>
       <p align = "center">Srinivasan</p>
logo: /assets/img/Logo.jpg
description: 
<p align="center">
<a href="https://www.linkedin.com/in/raghavendra-srinivasan-91a103127/">LinkedIn</a> |
<a href="https://github.com/Ray0705">GitHub</a>
  
<br>   
I'm RPA Developer and Junior Data Analysts..
Worked with rSutra Analytics and Consulting Pvt. Ltd.
I have more than 1 years of working expreince as Data Analyst and RPA Developer.
</br>
</p>
