title: <p align = "center">Raghavendra </p>
       <p align = "center">Srinivasan</p>
logo: /assets/img/Logo.jpg
description: 
A result-oriented Professional with 2.5+ years of experience and extensive knowledge of programming. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
