title: <p align="center"> Raghavendra </p>
       <p align="center"> Srinivasan </p>
logo: /assets/img/Logo.jpg

description: <p align="center"> Aspiring Data Scientist </p>



theme: jekyll-theme-minimal
