title: <p align = "center">Raghavendra </p>
       <p align = "center">Srinivasan</p>
logo: <p align = "center">/assets/img/Logo.jpg</p>
description: 
<p align = "center">
I am RPA Developer and Junior Data Analysts.
Worked with rSutra Analytics and Consulting Pvt. Ltd.
I have more than 1 years of working expreince as Data Analyst and RPA Developer.
</p>

theme: jekyll-theme-minimal
