
title: <p align="center"> Raghavendra </p>
       <p align="center"> Srinivasan </p>
       
logo: <img src="/assets/img/Logo.jpg" align="center">

description: <p align="center"> Aspiring Data Scientist </p>



theme: jekyll-theme-minimal
