title: <p align="center"> Raghavendra </p>
       <p align="center"> Srinivasan </p>
logo: <center> /assets/img/Logo.jpg </center>

description: <p align="center"> Aspiring Data Scientist </p>



theme: jekyll-theme-minimal
