title: <p align="center"> Raghavendra </p>
       <p align="center"> Srinivasan </p>
logo: <p align="center"> /assets/img/Logo.jpg </p>

description: <p align="center"> Aspiring Data Scientist </p>



theme: jekyll-theme-minimal
