title: <p align = "center">Raghavendra </p>
       <p align = "center">Srinivasan</p>
logo: /assets/img/Logo.jpg
description: 
<p align="center">
<a href="pdf/resume.pdf">Resume</a> |
<a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
<a href="https://github.com/sajankedia">GitHub</a>
  
<br>   
I'm RPA Developer and Junior Data Analysts..
Worked with rSutra Analytics and Consulting Pvt. Ltd.
I have more than 1 years of working expreince as Data Analyst and RPA Developer.
<br>
</p>
